# Generated by Django 5.1.4 on 2024-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment_parent_alter_comment_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
